mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 363
    end: -0.52
    stretchRatio: 0.9900990099009901
  - cells: 1000
    end: 3.48
    stretchRatio: 1.0
  - cells: 341
    end: 15.0
    stretchRatio: 1.01
- direction: y
  start: -15.0
  subDomains:
  - cells: 353
    end: -2.0
    stretchRatio: 0.9900990099009901
  - cells: 1000
    end: 2.0
    stretchRatio: 1.0
  - cells: 353
    end: 15.0
    stretchRatio: 1.01

flow:
  nu: 0.0005
  initialVelocity: [1.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 1.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.0004
  startStep: 0
  nt: 200000
  nsave: 2500
  nrestart: 10000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: snake
  file: snake2d35.body
